config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  root 'categories#index'

  resources :categories do
    resources :tasks, only: %i[edit create update destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: true,
                    uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :details, presence: true,
                      uniqueness: true,
                      length: { minimum: 10 }

  validate :priority_date_cannot_be_in_the_past, on: :create

  def priority_date_cannot_be_in_the_past
    errors.add(:priority, "can't be in the past") if priority.present? && priority < Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @categories = Category.where(user_id: current_user.id) if user_signed_in?
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    @category.update(user_id: current_user.id)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_url
  end

  private

  def category_params
    params.require(:category).permit(:title, :details, :user_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def edit
    @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])
  end

  def create
    @category = Category.find(params[:category_id])
    @task = @category.tasks.create(task_params)
    @task.update(user_id: current_user.id)

    redirect_to category_path(@category)
  end

  def update
    @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_back(fallback_location: root_path)
    else
      render action: 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])
    @task.destroy

    redirect_to category_path(@category)
  end

  private

  def task_params
    params.require(:task).permit(:details, :priority, :done, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <% if @category.errors.any? %>
    <div>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mb-3">
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
    <%= f.label :title %>
  </div>

  <div class="form-floating mb-3">
    <%= f.text_area :details, class: "form-control", placeholder: "Details" %>
    <%= f.label :details %>
  </div>

  <div>
    <%= f.submit :Submit, class: "btn btn-info" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="w-50 mx-auto">
  <h1>Edit Category</h1>
  <%= render 'form', category: @category %>
</div>

app/views/categories/index.html.erb
<%= provide(:categories_active, 'active') %>

<% if user_signed_in? %>
  <%= link_to 'New Category', new_category_path, class: "btn btn-primary float-end" %>
  <h2>Categories</h2>

  <p><%= 'Create a new category now!' if @categories.count == 0 %></p>

  <ul class="list-group">
    <% @categories.each do |category| %>
      <% if cycle("odd", "even") == "odd" %>
        <li class="list-group-item list-group-item-dark">
        <% else %>
          <li class="list-group-item">
          <% end %>

          <div class="float-md-end text-end mb-3 mb-md-0">
            <%= link_to 'Edit', edit_category_path(category), class: "btn btn-outline-secondary" %> |
            <%= link_to 'Delete', category_path(category),
                                method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: "btn btn-outline-danger" %>
          </div>

          <h3><%= link_to category.title, category, class: "link-dark" %></h3>
          <p><%= category.details %></p>

          <div class="card mt-4">
            <div class="card-body">
              <div class="float-sm-end text-end mb-2 mb-sm-0">
                <%= link_to "Add a Task", category, class: "btn btn-success" %>
              </div>

              <% if category.tasks.find { |t| t.priority == Date.current && t.user == current_user } %>
                <h6>Tasks for Today - <%= Date.current.strftime('%a, %d %b %Y') %></h6>

                <ul class="list-group mt-4">
                  <% category.tasks.each do |task| %>
                    <% if task.priority == Date.current %>
                      <% if cycle("odd", "even") == "odd" %>
                        <li class="list-group-item list-group-item-secondary">
                        <% else %>
                          <li class="list-group-item">
                          <% end %>
                          <%= render "tasks/done_form", task: task, category: category %>
                        </li>
                      <% end %>
                    <% end %>
                  </ul>
                <% else %>
                  <h6>No tasks for today.</h6>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="fs-2">
        Please <%= link_to 'log in', new_user_session_path, class: "link-success" %> to start building your journal!
        Or click <%= link_to 'here', new_user_registration_path, class: "link-secondary" %> if you don't have an account yet.
      </p>
    <% end %>

app/views/categories/new.html.erb
<div class="w-50 mx-auto">
  <h1>New Category</h1>
  <%= render 'form', category: @category %>
</div>

app/views/categories/show.html.erb
<div class="card">
  <div class="card-header">
    <div class="float-md-end text-end mb-3 mb-md-0">
      <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-outline-secondary" %> |
      <%= link_to 'Delete', category_path(@category),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: "btn btn-outline-danger" %>
    </div>

    <h1 class="card-title"><%= @category.title %></h1>
    <p class="card-text"><%= @category.details %></p>
  </div>

  <div class="card-body">
    <div id="task-accordion" class="accordion">
      <div class="accordion-item">
        <h2 id="overdue-title" class="accordion-header">
          <button class="accordion-button collapsed h2 fs-4 mb-0" type="button" data-bs-toggle="collapse" data-bs-target="#overdue-wrap" aria-expanded="true" aria-controls="overdue-wrap">
            Overdued Tasks

            <% if @category.tasks.find { |t| t.priority <= Date.current.yesterday } %>
              <span class="text-danger fs-6 ms-3">You have overdued tasks!</span>
            <% end %>
          </button>
        </h2>

        <div id="overdue-wrap" class="accordion-collapse collapse" aria-labelledby="overdue-title" data-bs-parent="#task-accordion">
          <ul class="list-group">
            <% unless @category.tasks.find { |t| t.priority <= Date.current.yesterday } %>
              <li class="list-group-item">Nothing else here yet.</li>
            <% end %>

            <% @category.tasks.each do |task| %>
              <% if task.priority <= Date.current.yesterday %>
                <%= render task %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="accordion-item">
        <h2 id="today-title" class="accordion-header">
          <button class="accordion-button h2 fs-4 mb-0" type="button" data-bs-toggle="collapse" data-bs-target="#today-wrap" aria-expanded="false" aria-controls="today-wrap">
            Tasks for Today - <%= Date.current.strftime('%a, %d %b %Y') %>
          </button>
        </h2>

        <div id="today-wrap" class="accordion-collapse collapse show" aria-labelledby="today-title" data-bs-parent="#task-accordion">
          <ul class="list-group">
            <% unless @category.tasks.find { |t| t.priority == Date.current } %>
              <li class="list-group-item">Nothing else here yet.</li>
            <% end %>

            <% @category.tasks.each do |task| %>
              <% if task.priority == Date.current %>
                <%= render task %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="accordion-item">
        <h2 id="future-title" class="accordion-header">
          <button class="accordion-button collapsed h2 fs-4 mb-0" type="button" data-bs-toggle="collapse" data-bs-target="#future-wrap" aria-expanded="false" aria-controls="future-wrap">
            Upcoming Tasks
          </button>
        </h2>

        <div id="future-wrap" class="accordion-collapse collapse" aria-labelledby="future-title" data-bs-parent="#task-accordion">
          <ul class="list-group">
            <% unless @category.tasks.find { |t| t.priority >= Date.current.tomorrow } %>
              <li class="list-group-item">Nothing else here yet.</li>
            <% end %>

            <% @category.tasks.each do |task| %>
              <% if task.priority >= Date.current.tomorrow %>
                <%= render task %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="card-footer">
    <%= render 'tasks/form' %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary bg-gradient mb-3">
  <div class="container">
    <a href="/" class="navbar-brand">Journal</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Categories', root_path, class: "nav-link #{yield(:categories_active)}" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <span id="nav-dropdown" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </span>

            <ul class="dropdown-menu" aria-labelledby="nav-dropdown">
              <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <% if controller_name == 'sessions' && action_name == 'new' %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!-- FAIR USE -->
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path("favicon-32x32.png") %>
    <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar'  %>

    <main>
      <div class="container">
        <% if notice %>
          <p class="notice alert alert-info w-75 mx-auto"><%= notice %></p>
        <% elsif alert %>
          <p class="alert alert-warning w-75 mx-auto"><%= alert %></p>
        <% end %>

        <div class="row justify-content-center">
          <% if controller.controller_name == 'categories' %>
            <div class="col-xl-8">
              <%= yield %>
            </div>
          <% else %>
            <%= yield %>
          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/tasks/_done_form.html.erb
<%= form_with model: [task.category, task], method: :patch do |f| %>
  <% if task.done? %>
    <%= f.check_box :done, checked: true, class: "btn-done form-check-input me-2" %>
  <% else %>
    <%= f.check_box :done, class: "btn-done form-check-input me-2" %>
  <% end %>

  <span><%= task.details %></span>

  <div class="float-md-end text-end mt-3 mt-md-0">
    <%= link_to 'Edit', edit_category_task_path(category, task), class: "btn btn-outline-secondary" %> |
    <%= link_to 'Delete', [task.category, task],
                          method: :delete,
                          data: { confirm: 'Are you sure?' },
                          class: "btn btn-outline-danger" %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: [@category, @category.tasks.build] do |f| %>
  <div class="row">
    <div class="col-md-7">
      <div class="form-floating">
        <%= f.text_area :details, class: "form-control", placeholder: "Details" %>
        <%= f.label :details %>
      </div>
    </div>

    <div class="col-sm-9 col-md-3 mt-2 mt-md-0">
      <div class="form-floating">
        <%= f.datetime_field :priority, id: 'datepicker', type: '', class: "form-control", placeholder: "Priority Date" %>
        <%= f.label :priority, 'Priority Date' %>
      </div>
    </div>

    <div class="col-sm-3 col-md-2 mt-2 mt-md-0 d-flex align-items-center">
      <%= f.submit "Add Task", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% if cycle("odd", "even") == "odd" %>
  <li class="list-group-item list-group-item-dark">
  <% else %>
    <li class="list-group-item">
    <% end %>

    <% if task.priority <= Date.current %>
      <%= render "tasks/done_form", task: task, category: @category %>
    <% else %>
      <%= task.priority.strftime('%a, %d %b %Y') %> - <%= task.details %>

      <div class="float-end">
        <%= link_to 'Edit', edit_category_task_path(@category, task), class: "btn btn-outline-secondary" %> |
        <%= link_to 'Delete', [task.category, task],
                          method: :delete,
                          data: { confirm: 'Are you sure?' },
                          class: "btn btn-outline-danger" %>
      </div>
    <% end %>
  </li>

app/views/tasks/edit.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with model: [@task.category, @task] do |f| %>
      <% if @task.errors.any? %>
        <div>
          <ul>
            <% @task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-floating d-inline-block w-50 align-middle">
        <%= f.text_area :details, class: "form-control", placeholder: "Details" %>
        <%= f.label :details %>
      </div>

      <div class="form-floating d-inline-block w-25 align-middle">
        <%= f.datetime_field :priority, id: 'datepicker', type: '', class: "form-control", placeholder: "Priority Date" %>
        <%= f.label :priority, 'Priority Date' %>
      </div>

      <%= f.submit "Update Task", class: "btn btn-success ms-3" %>
    <% end %>
  </div>
</div>